### ISSUE TITLE
Word Count Goals

### ISSUE THREAD

**Issue by kinabalu** [kinabalu/obsidian-word-sprint#13]

**Comment by leethobbit** [comment]
It would be really cool to see a progress bar somewhere that shows % completion of word count goals.  My reference here is scrivener, which shows two bars actually - one for your daily goal and one for your project goal.  This is currently the only feature from Scrivener that I really miss having and would love to see it here!

**Comment by SlRvb** [comment]
The option to set daily word count and/or a total word count would be really motivating to keep me writing. I say and/or because I may not have a total word could but do have a daily word count to hit, while others might have the inverse. 

---
I'd love to see a feature similar to mywriteclub for the side panel where stars are placed once you reach a certain word count:
![](https://user-images.githubusercontent.com/54087190/139568691-516b708b-011a-471f-b737-225bf1e5b4d8.png)
Hopefully it could be configurable how many words show a star. I just think it's really motivating to see that you've hit a certain amount of words rather than _just_ how many words you have left to go. It also doesn't have to be a star, the progress bar changing colors might be able to give off the same effect.

---
I also think Eleanor's suggestion with writemonkey and the little rectangle showing if you've reached your word count goal or exceeded it is also a fun idea: ![](https://media.discordapp.net/attachments/901911418801098842/904157819173998652/writemonkey.gif)

**Comment by kinabalu** [comment]
Will open up another issue and link to the idea of progress bars
