### ISSUE TITLE
Bug with pasting and cutting words

### ISSUE THREAD

**Issue by Rhydderch** [kinabalu/obsidian-word-sprint#47]
I noticed that pasting text was counted and added to the total words. Although this makes it very easy to reach my writing goals, it would be great if this way of counting words could be toggled in the settings. (It is probably related to #19 but I created this separate issue to make tracking easier)

Likewise, I also just noticed that start the timer in one note, then switching to another note counts this whole note as words written. And when starting a timer, it does not count words written in other notes.

Lastly, cutting pre-existing texts from the note, removes these words from the word count. It seems that this is a tricky problem to solve as this bug is also present with the "Better word count" plugin.

**Comment by MalignantCarp** [comment]
This is kind of tricky business. I've got it in mind for my own word statistics plugin, but I haven't been able to conceptualize a good way of handling this sort of behaviour.

The challenge here is that the means for counting words is to count the words in a file periodically and do the math on the change in word count within the file. So if you delete text (whether that is with delete, backspace, or cut), the words in the file have decreased, thus we count them as deleted. Similarly, with pasting, the words are increased, so words are added.

I've pondered this sort of dilemma a lot over the years with various plans to make my own writing software, but never really came up with a great answer to the problem. The other issue that crops up, too, is say you cut a piece of text with the intention of pasting it back in, but forget. You close the program or end up copying something else and now can't paste it in. Now if you're using version control, you can just check the diff, grab that text, and paste it back in wherever you intended to in that original session. Now ideally, this would have counted as moved words (for lack of a better qualifier), but if you had to retrieve it from outside, now you have a bit of a problem because you can't tell it was cut from somewhere in the project and not just newly added. What if you just happened to write it in a different application and were now pasting it in? It's new words and should be counted as words added. (This probably wouldn't be an issue in this particular context of the word sprint plugin, but for the topic in general...)

The only clear way I've been able to come up with in my mind is to track additional variables—words moved in and words moved out. That would be your paste and cut, respectively. The only caveat is you need a means of tracking when something is pasted in that may have been copied from elsewhere, because that needs a prompt of some kind to ask, "is this new material, or is this a paste from elsewhere in the project?" Short of keeping a log of everything cut, which I don't believe is possible from the plugin context, and matching that to what is being pasted it, I don't see a good means of doing that, which does give us a bit of a problem, at least in the context of tracking word statistics in general.

For the context of this plugin for word sprints, if there is a means of determining the number of words pasted or cut when such an action occurs, it is conceivable to implement an option wherein pasted content would be subtracted from the total word count and cut content would be added, thus nullifying their respective change to the total word count. This would definitely need to be implemented after or in conjunction to #19 due to the issues surrounding moving into different files. But that hinges entirely upon whether or not what was pasted or cut is available to the plugin context. You must remember also, the word count could be off if what was cut or pasted connected two words, as the words of the cut or pasted content would probably need to be counted separately. Short of monitoring CM6 for the cursor position, I don't see a way to correct for that, but it would only be off by 1 or 2 (potential word connections at the start and end).

Things become even more complicated if you consider the use of undo and redo, as I suspect they will result in word counts getting skewed. I don't really see any solution to that issue, short of watching for undo/redo events (if that's possible). The issue with that would be keeping a log of all word count deltas and trying to determine which ones need to be reversed after the undo/redo. I would suspect no plugin could handle that.

**Comment by kinabalu** [comment]
how large of an issue is this really? I understand the issue with multiple notes if that's the workflow and I'm pretty sure this is already a separate ticket?

There is a listener for paste actions, and it may be possible to listen for this and find a way to track and ignore those.

I just don't know that this plugin needs to cover every use case? We can add to the README so folks know that pasting in will affect the word count just like cutting will as well. A sprint is X minutes, and I don't want to overcomplicate the tracking by adding another variable for folks who pasted in. If you paste in, you effectively have added to your word count.

Thoughts?

**Comment by kinabalu** [comment]
Closing as it's certainly a use case but not one we want to track for a plugin meant for sprinting. Unless someone wants to take on a fix here.
