### ISSUE TITLE
Bug: Word Sprint includes all words in note at start of timer

### ISSUE THREAD

**Issue by SlRvb** [kinabalu/obsidian-word-sprint#53]
When trying to write in a note that already has the words, Word Sprint will add the total of the notes words into the word count when starting the sprint instead of only the ones written for this sprint.

Example of error:
![Obsidian_fGQSj2WIY6](https://user-images.githubusercontent.com/54087190/194929792-8bd7a2f1-2ad7-41e5-9347-3678e24fc8e3.gif)

**Comment by wagewarsgetrichdiegoncharov** [comment]
I'm also having this issue.

**Comment by dzhuyx** [comment]
Same here. Any solutions?

**Comment by kinabalu** [comment]
Can probably have the plugin check for text already and add it for removing from total. Will have to look into what the API provides and maybe there's a better way of calculating number of words written during that time period

**Comment by jmangelson** [comment]
I am having the same problem. Really excited about the plugin otherwise.

Looking at the code in main.ts (line 349) it looks like the previous word count is being stored (or at least potentially stored) at the beginning of the sprint. 
Is the bug that this if statement is failing? 

SprintRun.ts (lines 140-141, 102-113, 218) seems to implement the needed functionality already. 

@kinabalu Is it possible to check if the condition for the if statement that leads to main.ts (line 349) is evaluating to False?

**Comment by jmangelson** [comment]
Hi, Is there any update on this?

I really like the plugin, but would like to continue editing a single document for multiple sprints.

**Comment by Drakemoor** [comment]
Is there any solution for this?

**Comment by kinabalu** [comment]
this has been fixed in 0.2.5
